const crypto = require('crypto');
const config = require('../config.js');

/**
 * Provides AES-256-CBC encryption and decryption helpers for sensitive DB fields.
 */

const _encryptionKey = Buffer.from(config.ENCRYPTION_KEY, 'hex');

if (!_encryptionKey) {
  throw new Error('Encryption key is missing');
}

/**
 * Encrypts plain text using AES-256-CBC and prepends the IV.
 * @param {string} entity - Plain-text value to encrypt.
 * @returns {string} Encrypted payload formatted as `iv:ciphertext`.
 */
function encryptAES(entity) {

  // Generate a 16-byte initialization vector (IV).
    const iv = crypto.randomBytes(16);

    // Create a cipher using the configured key and generated IV.
    const cipher = crypto.createCipheriv('aes-256-cbc', _encryptionKey, iv);

    let encrypted = cipher.update(entity, 'utf8', 'hex');
    encrypted += cipher.final('hex');

    // Return the IV and encrypted data (IV is required for decryption).
    return iv.toString('hex') + ':' + encrypted;
}

  /**
   * Decrypts a payload generated by `encryptAES`.
   * @param {string} encryptedEntity - Encrypted payload formatted as `iv:ciphertext`.
   * @returns {string} Decrypted plain text value.
   */
function decryptAES(encryptedEntity) {
  
    // Separate IV and encrypted content.
    const parts = encryptedEntity.split(':');
    const iv = Buffer.from(parts[0], 'hex');
    const encryptedText = parts[1];

    // Create a decipher using the same key and extracted IV.
    const decipher = crypto.createDecipheriv('aes-256-cbc', _encryptionKey, iv);

    let decrypted = decipher.update(encryptedText, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return decrypted;
}

module.exports = {
    encryptAES,
    decryptAES
  }